name: Lint Commit Messages

on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
        with:
          helpURL: https://github.com/CodeToGather/TIPS-Backend/blob/main/CONTRIBUTING.md
